# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/node:16.2.0
    steps:
      - node/install:
          install-yarn: true 
          install-npm: false 
          node-version: '16.2.0' 

workflows:
  example-workflow:
    jobs:
      - example-job
      - node/test:
            pkg-manager: yarn 
            run-command: test
            version: '16.2.0'