# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/node:16.2.0
    steps:
      - node/install-packages:
          pkg-manager: yarn 

workflows:
  example-workflow:
    jobs:
      - example-job