export const PLUS_PER_CHILLI_DIAGONALLY_ADJACENT = 5;
export const PLUS_PER_CHILLI_WHEN_HARVEST = 8;
export const PLUS_PER_CHILLI_WHEN_HARVEST_WITH_ANOTHER_CROP = -4;
export const CHILLI_HARVEST_TURNS = () => {
  return [3, 4, 5, 14, 15, 16];
};
