export const PLUS_PER_TOMATOE_IN_MILPA = 2;
export const PLUS_PER_TOMATOE_WITH_TOMATILLO_OR_CHILLI_IN_MILPA = 2;
export const PLUS_IF_AT_LEAST_MIN_TOMATOE_IN_MILPA = 30;
export const MIN_TOMATOE_TO_SCORE_END_OF_GAME = 4;
export const TOMATOE_HARVEST_TURNS = () => {
  return [2, 4, 6, 8, 10, 12, 14];
};
