name: Issue workflow 👩🏽‍🌾👨🏼‍💻
on:
  issues:
    types: [opened, edited]

jobs:
  labeler:
    name: Labeler
    runs-on: ubuntu-latest
    steps:
      - uses: fuxingloh/multi-labeler@v1
        with: 
          github-token: ${{secrets.TOKEN}}
